version: '3.3'

services:

  db:
    image: mysql:5.7
    environment:
      PMA_ARBITRARY: 1
      MYSQL_PASSWORD:
      MYSQL_ROOT_PASSWORD: ${DOCKER_DATABASE_USER}
    command: mysqld --sql_mode=""
    volumes:
      - .db:/var/lib/mysql
    ports:
      - ${DOCKER_MYSQL_PORT}:3306

  blog_phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      MYSQL_USER: ${DOCKER_DATABASE_USER}
      MYSQL_PASSWORD: ${DOCKER_DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DOCKER_DATABASE_USER}
    ports:
      - ${DOCKER_PHPMYADMIN_PORT}:80
    links:
      - db

  blog_app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: 'blog'
    ports:
      - ${DOCKER_APACHE_PORT_HTTP}:80
      - ${DOCKER_VITE_PORT}:5173
    volumes:
      - ./app:/var/www/html


